module.exports = {
  darkMode: "class",
  content: ["./index.html", "./assets/js/**/*.js"],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#93000b",
        "tertiary-container": "#991b1b",
        "secondary-fixed": "#6ffbbe",
        "secondary": "#4edea3",
        "inverse-on-surface": "#2c3039",
        "error-container": "#93000a",
        "background": "#090a0f",
        "surface": "#0d0e12",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-highest": "#282a32",
        "tertiary-fixed-dim": "#ffb4ac",
        "on-secondary-fixed": "#002113",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#06070a",
        "surface-dim": "#090a0f",
        "inverse-primary": "#dc2626",
        "on-tertiary-fixed-variant": "#7f1d1d",
        "tertiary": "#f87171",
        "secondary-container": "#00a572",
        "surface-variant": "#22252e",
        "on-secondary": "#003824",
        "surface-container-low": "#111318",
        "on-surface": "#f1f2f6",
        "tertiary-fixed": "#fecaca",
        "on-tertiary-fixed": "#450a0a",
        "surface-bright": "#2e323b",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#dfe2ee",
        "surface-container-high": "#1c1f27",
        "surface-tint": "#ef4444",
        "on-secondary-container": "#00311f",
        "primary-fixed": "#fee2e2",
        "on-tertiary-container": "#fee2e2",
        "outline": "#958da1",
        "outline-variant": "#4a4455",
        "surface-container": "#161820",
        "on-primary-container": "#fffbff",
        "on-surface-variant": "#ccc3d8",
        "error": "#ffb4ab",
        "on-error": "#ffffff",
        "primary": "#dc2626",
        "primary-container": "#dc2626",
        "on-primary-container": "#fff6f5",
        "background": "#090a0f",
        "on-background": "#e5e1e4",
        "surface-variant": "#22252e"
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px"
      },
      spacing: {
        "gutter-mobile": "1rem",
        "gutter-desktop": "2rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "space-4xl": "6rem",
        "space-5xl": "8rem",
        "container-max": "1280px"
      },
      fontFamily: {
        "display-xl": ["Plus Jakarta Sans"],
        "display-xl-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "code-sm": ["JetBrains Mono"]
      },
      fontSize: {
        "display-xl": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-xl-mobile": ["40px", { lineHeight: "46px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "code-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }]
      }
    }
  },
  plugins: []
};
